-- MySQL Script generated by MySQL Workbench
-- Wed Feb  5 14:11:14 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema guitarshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guitarshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guitarshop` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `guitarshop` ;

-- -----------------------------------------------------
-- Table `guitarshop`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guitarshop`.`product` (
  `id` VARCHAR(255) NOT NULL,
  `amount` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `discount` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `price` INT(11) NULL DEFAULT NULL,
  `updatedDate` VARCHAR(255) NULL DEFAULT NULL,
  `weight` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `guitarshop`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guitarshop`.`supplier` (
  `id` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `contact` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `tel` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `guitarshop`.`product_supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guitarshop`.`product_supplier` (
  `productId` VARCHAR(225) NOT NULL,
  `supplierId` VARCHAR(225) NOT NULL,
  PRIMARY KEY (`productId`, `supplierId`),
  INDEX `fk-supplier` (`supplierId` ASC) VISIBLE,
  CONSTRAINT `fk-product`
    FOREIGN KEY (`productId`)
    REFERENCES `guitarshop`.`product` (`id`),
  CONSTRAINT `fk-supplier`
    FOREIGN KEY (`supplierId`)
    REFERENCES `guitarshop`.`supplier` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
